import os

base_dir = r"c:\Users\adity\Desktop\Projects\Soulamore-Website\reports"

# 1. Setup assignee folders in reports/testing/03-in-progress and 04-testing-verification
assignees = ["ADITYA", "ABHISHEK", "ARYAN", "YASHMEET"]
for assignee in assignees:
    for status in ["03-in-progress", "04-testing-verification"]:
        path = os.path.join(base_dir, "testing", status, assignee)
        os.makedirs(path, exist_ok=True)
        # Create .gitkeep to track in git
        with open(os.path.join(path, ".gitkeep"), "w") as f:
            f.write("# Keep folder tracked in git\n")
        print(f"Created: {path}")

# 2. Setup user folders in reports/
agents = ["ANTIGRAVITY", "CODEX", "CURSOR", "KILOCODE", "OPENCODE", "QWEN"]

def setup_user_reports(user_name):
    user_path = os.path.join(base_dir, user_name)
    os.makedirs(user_path, exist_ok=True)
    for agent in agents:
        agent_path = os.path.join(user_path, agent)
        os.makedirs(agent_path, exist_ok=True)
        with open(os.path.join(agent_path, ".gitkeep"), "w") as f:
            f.write("# Keep folder tracked in git\n")
            
    # Write manifest file
    manifest_path = os.path.join(user_path, "MANIFEST.md")
    manifest_content = f"""# Soulamore: {user_name} Reports Manifest

This manifest tracks all formal reports generated by specialist agents for {user_name}.

## 🤖 ANTIGRAVITY Reports
| ID | Date | Type | Title |
| :--- | :--- | :--- | :--- |
| ... | ... | ... | (No reports yet) |

| Index | Date | Agent | Type | Description | Link |
| :--- | :--- | :--- | :--- | :--- | :--- |
"""
    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write(manifest_content)
    print(f"Setup reports directory and Manifest for: {user_name}")

setup_user_reports("ABHISHEK")
setup_user_reports("ARYAN")
setup_user_reports("YASHMEET")
